version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "16:00"
  open-pull-requests-limit: 10
  target-branch: development
