name: Build and publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
  push:
    branches:
    - development

env:
  BUILD_PLATFORMS: "linux/amd64,linux/arm64"

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      -
        name: Checkout Code
        uses: actions/checkout@v4.1.1

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          images: |
            ghcr.io/yubiuser/webchanges
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,enable=${{ github.event_name == 'workflow_dispatch' }}
            type=ref,event=pr
            type=ref,event=branch
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
